### PR TITLE
Feature/issue 298

### PR DESCRIPTION
**Pull request by diegodewilde**
#298

### CODE REVIEW

**Review by DemianD — CHANGES_REQUESTED** [review]
The buttons bump all the time 👎 
I guess then it's even better without the effect. If needed we can merge it tomorrow

**Comment by diegodewilde** [comment]
@DemianD  Was beforehand as I remembered 🤔

**Comment by DemianD** [comment]
@diegodewilde , will first look at the ranking, afterwards to the effect (if time left)

**Comment by diegodewilde** [comment]
@Demian Will take a look myself based on develop now. (effect)

**Review by DemianD — APPROVED** [review]

**Pull request merged**
