### PR TITLE
Maintenance.md added

### PR DESCRIPTION
**Pull request by mrvdries**
Some info on troubleshooting a technical issue with maintaining the project based on the experience from an outsider with some help from people who worked on the project.

### CODE REVIEW

**Review by DylanVanAssche — APPROVED** [review]

**Comment by DylanVanAssche** [comment]
@DemianD CI checks runnen niet?

**Comment by DemianD** [comment]
@DylanVanAssche, I guess because this repo was forked and immediately pushed the commits in develop. Maybe because it was forked, the webhooks can't fetch the correct repo. I'll see what I can do

**Comment by DemianD** [comment]
I've disabled the CI checks for now.

**Comment by DylanVanAssche** [comment]
Thanks @DemianD !

**Pull request merged**
